// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Z0XXo9ZOLK5H2EGP8zMsB1_VulVxOQg',
    appId: '1:563064977021:web:f6454caa16c22c4c612314',
    messagingSenderId: '563064977021',
    projectId: 'chatup3-38e1e',
    authDomain: 'chatup3-38e1e.firebaseapp.com',
    storageBucket: 'chatup3-38e1e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIm2V5eH89qGm_07vjUHfFF2W3d9YAErU',
    appId: '1:563064977021:android:09879aa2a767282f612314',
    messagingSenderId: '563064977021',
    projectId: 'chatup3-38e1e',
    storageBucket: 'chatup3-38e1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrTfrfprHxl67hqIQUxzFlX7HREsnuDRo',
    appId: '1:563064977021:ios:43ad29e3b30f7c4b612314',
    messagingSenderId: '563064977021',
    projectId: 'chatup3-38e1e',
    storageBucket: 'chatup3-38e1e.firebasestorage.app',
    iosBundleId: 'com.example.flashChatDubl3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrTfrfprHxl67hqIQUxzFlX7HREsnuDRo',
    appId: '1:563064977021:ios:43ad29e3b30f7c4b612314',
    messagingSenderId: '563064977021',
    projectId: 'chatup3-38e1e',
    storageBucket: 'chatup3-38e1e.firebasestorage.app',
    iosBundleId: 'com.example.flashChatDubl3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0Z0XXo9ZOLK5H2EGP8zMsB1_VulVxOQg',
    appId: '1:563064977021:web:c1d3972beb01576d612314',
    messagingSenderId: '563064977021',
    projectId: 'chatup3-38e1e',
    authDomain: 'chatup3-38e1e.firebaseapp.com',
    storageBucket: 'chatup3-38e1e.firebasestorage.app',
  );
}
